# Start with a base Python image
FROM python:3.10-slim

# Install necessary libraries for GUI applications
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libegl1-mesa \
    libxrandr2 \
    libxss1 \
    libxcursor1 \
    libxcomposite1 \
    libasound2 \
    libxi6 \
    libxtst6 \
    libxkbcommon-x11-0 \
    libdbus-1-3 \
    qtbase5-dev \
    qtchooser \
    qt5-qmake \
    qtbase5-dev-tools \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Create and activate a virtual environment
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip and install Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the main Python script
COPY main.py ./

# Set the DISPLAY environment variable to use host X11 server
ENV DISPLAY=host.docker.internal:0

# Command to run the main Python script
CMD ["python3", "main.py"]
