FROM python:3.10

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install Python dependencies
COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the Streamlit application script
COPY app.py ./

# Expose port 8501 for Streamlit
EXPOSE 8501

# Command to run the Streamlit application
CMD ["streamlit", "run", "app.py"]
